version: '3.8'

services:
  postgresql:
    image: postgres:13-alpine
    container_name: service-postgres
    environment:
      POSTGRES_DB: product_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r75q107GE6fI
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  product-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-management-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/product_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=r75q107GE6fI
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      postgresql:
        condition: service_healthy
volumes:
  db_data: